name: Go

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.html"
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.html"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: "1.15"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Test
      run: go test -race ./...

    - name: Build
      run: go build -v ./cmd/market
