name: Tests

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.html"
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.html"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: "1.15"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Test
      run: go test -race -covermode atomic -coverprofile=profile.cov ./...

    - name: Build
      run: go build -v ./cmd/market

    - name: Code coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
