name: Go

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.html"
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.html"

jobs:

  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: "1.15"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify dependencies
      run: |
        go mod verify
        go mod download

    - name: Run checks
      run: ./scripts/ci-lint.sh
